// Do not edit this file. It is automatically generated by Supabase.
// If you need to add a new enum, add it /core/enums/core_enums.dart

import 'package:collection/collection.dart';

extension FFEnumExtensions<T extends Enum> on T {
  String serialize() => name;
}

extension FFEnumListExtensions<T extends Enum> on Iterable<T> {
  T? deserialize(String? value) =>
      firstWhereOrNull((e) => e.serialize() == value);
}

T? deserializeEnum<T>(String? value) {
  switch (T) {
    default:
      return null;
  }
}

